name: yaru_window_example
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: '>=3.7.0'

dependencies:
  flex_color_picker: ^3.1.0
  flutter:
    sdk: flutter
  handy_window: ^0.3.0
  yaru: ^0.5.0
  yaru_window:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
