name: yaru_window_linux
description: A Linux implementation of yaru_window.
repository: https://github.com/ubuntu/yaru_window.dart
issue_tracker: https://github.com/ubuntu/yaru_window.dart/issues
version: 0.2.2

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  ubuntu_lints: ^0.4.1+1

flutter:
  plugin:
    implements: yaru_window
    platforms:
      linux:
        pluginClass: YaruWindowLinuxPlugin
