name: yaru_window_web
description: A stub implementation of yaru_window for Web.
repository: https://github.com/ubuntu/yaru_window.dart
issue_tracker: https://github.com/ubuntu/yaru_window.dart/issues
version: 0.0.3+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  yaru_window_platform_interface: ^0.1.2+1

dev_dependencies:
  ubuntu_lints: ^0.4.1+1

flutter:
  plugin:
    implements: yaru_window
    platforms:
      web:
        pluginClass: YaruWebWindow
        fileName: src/web_window.dart
