name: yaru_window_example
publish_to: 'none'

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flex_color_picker: ^3.5.1
  flutter:
    sdk: flutter
  handy_window: ^0.4.0
  yaru: ^5.2.0
  yaru_window: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  ubuntu_lints: ^0.4.0

flutter:
  uses-material-design: true
